sudo: required
services:
  - docker

before_install:
  - docker build -t vygos/docker-react -f Dockerfile.dev .
  - docker build -t vygos/docker-react-prod .
  - docker run -d -e TEST=$TEST vygos/docker-react-prod

script:
  - docker run -e CI=true vygos/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-855433857104"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY